Repository OmokNoonE/OnionHotSayYo-frontend, pull requests merged in 2024-04, with the labels that each got.

#1 [PR] carousel 구현
  OnionHotSayYo_frontend/src/assets/banner/sample_img.png
  OnionHotSayYo_frontend/src/assets/carousel.css
  OnionHotSayYo_frontend/src/components/carousel.vue
Labels: feat

#2 [PR] table 구현
  OnionHotSayYo_frontend/src/App.vue
  OnionHotSayYo_frontend/src/components/table.vue
Labels: feat

#6 [PR] 회원가입 페이지 화면 구현
  OnionHotSayYo_frontend/src/App.vue
  OnionHotSayYo_frontend/src/assets/checkout.css
  OnionHotSayYo_frontend/src/assets/js/checkout.js
  OnionHotSayYo_frontend/src/components/SignUp/signup.vue
  OnionHotSayYo_frontend/src/main.js
Labels: feat

#7 [PR] 게시글 세부내용 화면 구현
  OnionHotSayYo_frontend/src/App.vue
  OnionHotSayYo_frontend/src/components/Section/post/detail/detailUnion.vue
Labels: feat

#8 [PR| 각 페이지 세부 요소 수정 및 개인 페이지 추가
  OnionHotSayYo_frontend/index.html
  OnionHotSayYo_frontend/public/OnionHotSayYo.ico
  OnionHotSayYo_frontend/src/assets/image/OmokProfile.png
  OnionHotSayYo_frontend/src/assets/svg/search.svg
  OnionHotSayYo_frontend/src/components/Footer/Footerbody/Footerbody.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderProfile.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderUpper.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/SearchBar.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/PersonalPage.vue
  OnionHotSayYo_frontend/src/components/Section/SectionAll.vue
  OnionHotSayYo_frontend/src/components/Section/sample.vue
  OnionHotSayYo_frontend/src/components/Section/table.vue
Labels: feat

#9 [PR] offcanvas 기능 구현, Login 화면 구현, Footer 수정
  OnionHotSayYo_frontend/src/assets/image/github.png
  OnionHotSayYo_frontend/src/assets/image/notion.png
  OnionHotSayYo_frontend/src/components/Footer/Footerbody/Footerbody.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderLogin.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderProfile.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderUpper.vue
Labels: feat

#10 [PR] personal page 보강 작업
  OnionHotSayYo_JsonServer/member.json
  OnionHotSayYo_JsonServer/members.json
  OnionHotSayYo_frontend/package.json
  OnionHotSayYo_frontend/src/App.vue
  OnionHotSayYo_frontend/src/components/Section/Loading/Loading.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/PersonalPage.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyBookmark.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyComment.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyFollow.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyFollower.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyLike.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyPost.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/ProfileContentsUnion.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileHeader.vue
  OnionHotSayYo_frontend/src/main.js
  OnionHotSayYo_frontend/src/router/router.js
  OnionHotSayYo_frontend/src/views/MainPageView.vue
  OnionHotSayYo_frontend/src/views/MyPageView.vue
  OnionHotSayYo_frontend/src/views/NotFound.vue
  OnionHotSayYo_frontend/src/views/PersonalListView.vue
  OnionHotSayYo_frontend/src/views/PersonalPageView.vue
  OnionHotSayYo_frontend/src/views/PostDetailView.vue
  OnionHotSayYo_frontend/src/views/PostListView.vue
  OnionHotSayYo_frontend/src/views/SectionView.vue
Labels: bug, enhancement, feat

#15 [PR] 쪽지 페이지 구현
  OnionHotSayYo_JsonServer/letters.json
  OnionHotSayYo_frontend/src/components/Section/Letter/ReceiveList.vue
  OnionHotSayYo_frontend/src/components/Section/Letter/SendList.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/ProfileContentsUnion.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileHeader.vue
  OnionHotSayYo_frontend/src/router/router.js
  OnionHotSayYo_frontend/src/views/LetterView.vue
  OnionHotSayYo_frontend/src/views/MainPageView.vue
  OnionHotSayYo_frontend/src/views/MyPageView.vue
Labels: feat

#17 [PR] 알림 기능 테스트 코드
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderProfile.vue
  OnionHotSayYo_frontend/src/components/Section/Main/BestPost.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyBookmark.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyComment.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyLike.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyPost.vue
  OnionHotSayYo_frontend/src/components/Section/Post/Detail/PostDetailUnion.vue
  OnionHotSayYo_frontend/src/components/Section/Post/List/PostListBody.vue
  OnionHotSayYo_frontend/src/views/MyPageView.vue
  OnionHotSayYo_frontend/src/views/PostListView.vue
  OnionHotSayYo_frontend/src/views/SseTest.vue
  OnionHotSayYo_frontend/vite.config.js
Labels: feat

#18 [PR] 페이지네이션 및 CKEditor 기능 추가
  OnionHotSayYo_frontend/package-lock.json
  OnionHotSayYo_frontend/package.json
  OnionHotSayYo_frontend/src/UploadAdapter.js
  OnionHotSayYo_frontend/src/components/Section/Post/Add/AddPostDetail.vue
  OnionHotSayYo_frontend/src/components/Section/Post/Add/AddPostUnion.vue
  OnionHotSayYo_frontend/src/components/Section/Post/List/PostListBody.vue
  OnionHotSayYo_frontend/src/main.js
  OnionHotSayYo_frontend/src/router/router.js
  OnionHotSayYo_frontend/src/views/AddPostView.vue
  OnionHotSayYo_frontend/vite.config.js
Labels: feat

#19 [PR] 로그인, 로그아웃 기능
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderLogin.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderLogout.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderUpper.vue
  OnionHotSayYo_frontend/src/js/axios-instance.js
  OnionHotSayYo_frontend/src/main.js
  OnionHotSayYo_frontend/src/store/index.js
  OnionHotSayYo_frontend/src/views/SignUpView.vue
Labels: feat

#21 [PR] 로그인 상태 유지 및 router 연결
  OnionHotSayYo_frontend/package.json
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderLogin.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderLogout.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderProfile.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderUpper.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileHeader.vue
  OnionHotSayYo_frontend/src/js/axios-instance.js
  OnionHotSayYo_frontend/src/main.js
  OnionHotSayYo_frontend/src/router/router.js
  OnionHotSayYo_frontend/src/store/index.js
  OnionHotSayYo_frontend/src/views/MyPageView.vue
Labels: feat

#22 [PR] SSE 연결, 알림 기능 설정
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderLogin.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderProfile.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderUpper.vue
  OnionHotSayYo_frontend/src/store/index.js
Labels: feat

#24 [PR] 게시글 작성페이지 기능 구현(CKEditor5)
  OnionHotSayYo_frontend/package-lock.json
  OnionHotSayYo_frontend/package.json
  OnionHotSayYo_frontend/src/UploadAdapter.js
  OnionHotSayYo_frontend/src/components/Section/Post/Add/AddPostDetail.vue
  OnionHotSayYo_frontend/src/components/Section/Post/Add/AddPostUnion.vue
  OnionHotSayYo_frontend/src/components/Section/Post/Detail/PostDetailTop.vue
  OnionHotSayYo_frontend/src/components/Section/Post/Detail/PostDetailUnion.vue
  OnionHotSayYo_frontend/src/components/Section/Post/List/PostListBody.vue
  OnionHotSayYo_frontend/src/main.js
  OnionHotSayYo_frontend/src/router/router.js
Labels: feat

#25 [PR] datetime 및 mypage 좋아요 표기구현
  OnionHotSayYo_frontend/package-lock.json
  OnionHotSayYo_frontend/package.json
  OnionHotSayYo_frontend/src/components/Section/Main/BestPost.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyBookmark.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyComment.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyFollow.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyFollower.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyLike.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/MyPost.vue
  OnionHotSayYo_frontend/src/components/Section/PersonalPage/Profile/ProfileContents/ProfileContentsUnion.vue
  OnionHotSayYo_frontend/src/components/Section/Post/Detail/PostDetailUnion.vue
  OnionHotSayYo_frontend/src/views/LetterView.vue
  OnionHotSayYo_frontend/src/views/MyPageView.vue
  OnionHotSayYo_frontend/src/views/PersonalListView.vue
  OnionHotSayYo_frontend/src/views/PostListView.vue
  OnionHotSayYo_frontend/src/views/SearchListView.vue
Labels: feat

#27 [PR] signup 페이지 이동 기능 추가
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderLogin.vue
  OnionHotSayYo_frontend/src/components/Header/HeaderUpper/HeaderProfile.vue
  OnionHotSayYo_frontend/src/router/router.js
  OnionHotSayYo_frontend/src/views/SignUpView.vue
Labels: feat

#28 [PR] 메인화면에 의도한 API로 통신 하도록 개선
  OnionHotSayYo_frontend/src/components/Section/Main/BestPost.vue
Labels: enhancement
